task:
  name: FreeBSD
  freebsd_instance:
    image_family: freebsd-13-2
  install_script: pkg install -y meson pkgconf libfmt liblz4 libyaml rapidjson googletest rhash python3 py39-cython py39-pytest py39-pytest-timeout py39-yaml py39-lz4 py39-decorator
  script: |
    set -e
    meson build
    ninja -vC build
    cd python
    python3 setup.py build_ext --inplace --library-dirs=../build/src --rpath=`pwd`/../build/src

  test_script: |
    set -e
    meson test --no-suite slow -C build --no-rebuild --print-errorlogs
    cd python
    python3 -m pytest --log-level=DEBUG --timeout 60 -v || true # Not all tests are passing on FreeBSD now
